### ISSUE TITLE
spurious jre package requirement

### ISSUE THREAD

**Issue by petere** [rtyler/puppet-jenkins#31]
In `manifests/init.pp`, there is a package `jre` being required.  That package does not exit on Debian.  Even though it's only a noop, it produces useless output.

It was introduced in

```
commit 89295d54bcf0f890fe3043f42ae7663dedec9b07
Author: Jean-François Roche <jfroche@affinitic.be>
Date:   Mon Feb 6 11:57:47 2012 +0100

    fix style using puppet-lint
```

which doesn't explain much.

**Comment by rtyler** [comment]
Thanks!

As soon as Puppet Forge cooperates, 0.2.4 which contains this fix will be uploaded there, otherwise the latest HEAD of master contains it.
