### ISSUE TITLE
Jenkins user problems

### ISSUE THREAD

**Issue by ThePixelDeveloper** [rtyler/puppet-jenkins#47]
Hi,

There's a bug in user creation where if the user created in `::plugin` is called before the package is installed then the package created user is ignored and errors occur.

This means that the home directory for `jenkins` doesn't exist (when it should be /var/lib/jenkins) so it becomes a problem when jenkins is looking in the `~/.ssh` directory for picking up SSH keys.

Hope that makes sense.

I'll create a patch if it's required, I personally think the plugins installation should require jenkins to be installed first.

**Comment by matthewbarr** [comment]
I think the hope was to keep the plugin class usable even if you didn't use the rest of the module.

The fix might be in the same fix as issue 46.
